apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-logging
  namespace: kube-system
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-logging
            image: dirivio/python-pod-logs
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
